//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anketaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer_table_else
    {
        public int id { get; set; }
        public int id_table_question_else { get; set; }
        public int id_table_variant { get; set; }
        public int id_user { get; set; }
    
        public virtual table_question_else table_question_else { get; set; }
        public virtual table_variant table_variant { get; set; }
        public virtual user user { get; set; }
    }
}
