//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anketaApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class anketaEntities : DbContext
    {
        public anketaEntities()
            : base("name=anketaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer_else> answer_else { get; set; }
        public virtual DbSet<answer_table> answer_table { get; set; }
        public virtual DbSet<answer_table_else> answer_table_else { get; set; }
        public virtual DbSet<answer_text> answer_text { get; set; }
        public virtual DbSet<answer_variant> answer_variant { get; set; }
        public virtual DbSet<form> form { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<question_else> question_else { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<table_question> table_question { get; set; }
        public virtual DbSet<table_question_else> table_question_else { get; set; }
        public virtual DbSet<table_variant> table_variant { get; set; }
        public virtual DbSet<type_question> type_question { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<variant> variant { get; set; }
    }
}
